# src/config.yaml
# Modified for Kohaku Lab

site:
  # Your Lab's Name
  name: Kohaku Lab
  # Your Lab's Live URL (Update when deployed)
  site: 'https://kohaku-lab.org'
  # Base path (usually '/')
  base: '/'
  # Astro default is false, usually preferred. Set to true if you need trailing slashes.
  trailingSlash: false

  # Optional: Add your Google Site Verification ID for Google Search Console
  googleSiteVerificationId: false # or 'YOUR_GOOGLE_VERIFICATION_ID'

# Default SEO metadata used across the site
metadata:
  title:
    # Default title for pages that don't override it
    default: Kohaku Lab
    # Template for page titles (%s will be replaced by the page title)
    template: '%s — Kohaku Lab'
  # Default meta description (important for SEO) - **UPDATE THIS**
  description: 'Kohaku Lab pioneers cutting-edge research and development in Artificial Intelligence, focusing on creating intelligent systems that solve real-world problems and drive innovation.'
  # Default robots directive (allow indexing by default)
  robots:
    index: true
    follow: true
  # OpenGraph metadata for social sharing (Facebook, LinkedIn, etc.)
  openGraph:
    # Should match site.name
    site_name: Kohaku Lab
    # Default image for sharing links - **REPLACE THIS IMAGE**
    images:
      - url: '~/assets/images/default.png' # Path relative to src/
        width: 1200
        height: 628
    type: website # Usually 'website' for home, 'article' for posts
  # Twitter card metadata - **UPDATE HANDLES or remove**
  twitter:
    handle: '@KohakuLabAI' # Replace with your lab's X/Twitter handle
    site: '@KohakuLabAI' # Replace with your lab's X/Twitter handle
    cardType: summary_large_image

# Internationalization settings
i18n:
  language: en # Default language
  textDirection: ltr # Left-to-Right text direction

# Configure specific applications like the Blog/News section
apps:
  blog: # Renamed to handle 'News'
    isEnabled: true # Enable the News section
    postsPerPage: 6 # How many news items per page
    isRelatedPostsEnabled: true # Show related news items?
    relatedPostsCount: 4 # How many related items to show

    # Settings for individual news posts
    post:
      isEnabled: true # Allow individual news pages
      # Permalink structure for news items - **IMPORTANT**
      permalink: '/news/%slug%' # URL like kohaku-lab.org/news/your-post-slug
      robots:
        index: true
        follow: true

    # Settings for the main news listing page
    list:
      isEnabled: true # Enable the main /news page
      pathname: 'news' # The base URL path for the news section
      robots:
        index: true
        follow: true

    # Disable Categories and Tags for News unless needed
    category:
      isEnabled: false
      pathname: 'category' # Path if enabled: /news/category/your-category
      robots:
        index: false
        follow: true

    tag:
      isEnabled: false
      pathname: 'tag' # Path if enabled: /news/tag/your-tag
      robots:
        index: false
        follow: true

# Analytics configuration
analytics:
  vendors:
    googleAnalytics:
      # Add your Google Analytics ID (G-XXXXXXXXXX) or keep null
      id: null
      # Use Partytown for better performance (recommended)
      partytown: true

# User Interface settings
ui:
  # Theme behavior: 'system' respects OS, 'light' or 'dark' forces theme
  theme: 'system'
